### ISSUE TITLE
Roman Quantizer missing voltages

### ISSUE THREAD

**Issue by anaday** [nicholas-j-denning/NullSet#1]
See screenshot.

I'm sending C major triad in and not getting a C triad out on the I chord. The other chords are off or missing components as well.

![roman_screen](https://github.com/user-attachments/assets/f7587fd6-eb8f-412e-868d-cf9532f67c3d)

Love that you made this! Looking forward to seeing it fixed.

Thanks

**Comment by nicholas-j-denning** [comment]
Hi. Thank you for your interest and your bug report.

This is actually the intended behavior because it is a uniform quantizer where every note has an evenly sized range of inputs. So, for a C major chord, [0,0.333) quantizes to C, [0.333, 0.666) to E, and [0.666,1.0) to G. 

This behavior makes it so that random input voltages will be evenly distributed between each note, and so that sending in triangle or saw LFO produces an evenly timed arpeggio. 

I have changed the README.md to explain this.

**Comment by anaday** [comment]
Oh! I see now. Thanks for the clarification.
